function main_train_validate_unfortunate(...
  n_layers_number_of_neurons,...
  n_layers_transfer_functions,...
  learning_rate,...
  iterations)

%% load the spam data
load('spam_data.mat');

%% Preprocessing
train_set = P_train;
train_set_class = T_train;

% Split to train_set and validation_set
validation_set = train_set(:, size(train_set, 2) - 919:size(train_set, 2));
validation_set_class = train_set_class(:, size(train_set_class, 2) - 919:size(train_set_class, 2));

train_set = train_set(:, 1:size(train_set, 2) - 920);
train_set_class = train_set_class(:, 1:size(train_set_class, 2) - 920);

%% Get misclassification error
err = spam(...
    train_set,...
    train_set_class,...
    validation_set,...
    validation_set_class,...
    n_layers_number_of_neurons,...
    n_layers_transfer_functions,...
    learning_rate,...
    iterations);

fprintf('misclassification error: %f', err);

end