clear; clc; close all;

%% Setting up variables
n_layers_number_of_neurons = [3, 2, 1];
n_layers_transfer_functions = {'tansig', 'tansig', 'tansig'};
learning_rate = 0.01;
iterations = 10000;

main_train_validate_unfortunate(...
  n_layers_number_of_neurons,...
  n_layers_transfer_functions,...
  learning_rate,...
  iterations);

main_train_validate_test(...
  n_layers_number_of_neurons,...
  n_layers_transfer_functions,...
  learning_rate,...
  iterations);
