clear; clc; close all;

%% Setting up variables
n_layers_number_of_neurons = [10, 10, 1];
n_layers_transfer_functions = {'tansig', 'tansig', 'tansig'};
learning_rate = 0.1;
iterations = 1000;

main_train_validate(...
  n_layers_number_of_neurons,...
  n_layers_transfer_functions,...
  learning_rate,...
  iterations);

pause

main_train_validate_test(...
  n_layers_number_of_neurons,...
  n_layers_transfer_functions,...
  learning_rate,...
  iterations);
