function main_train_validate(...
  n_layers_number_of_neurons,...
  n_layers_transfer_functions,...
  learning_rate,...
  iterations)

%% Load data
load('california_data');
train_set = P_train;
train_set_class = T_train;

%% Split data
% 16.67% test_set, 16.67% validation_set, 66.67% train_set
validation_set = train_set(:, size(train_set, 2) - 4127:size(train_set, 2));
validation_set_class = train_set_class(:, size(train_set_class, 2) - 4127:size(train_set_class, 2));

train_set = train_set(:, 1:size(train_set, 2) - 4128);
train_set_class = train_set_class(:, 1:size(train_set_class, 2) - 4128);

err = house(...
    train_set,...
    train_set_class,...
    validation_set,...
    validation_set_class,...
    n_layers_number_of_neurons,...
    n_layers_transfer_functions,...
    learning_rate,...
    iterations);

fprintf('misclassification error: %f', err);

end