function main_train_validate_test(...
  n_layers_number_of_neurons,...
  n_layers_transfer_functions,...
  learning_rate,...
  iterations)

%% load the housing data
load('california_data');

%% Preprocessing
train_set = P_train;
train_set_class = T_train;

test_set = P_test;
test_set_class = T_test;

%% Get misclassification error
err = house(...
    train_set,...
    train_set_class,...
    test_set,...
    test_set_class,...
    n_layers_number_of_neurons,...
    n_layers_transfer_functions,...
    learning_rate,...
    iterations);

fprintf('misclassification error: %f', err);

end